data:
  train_files: hiyouga/math12k@train
  val_files: hiyouga/math12k@test
  prompt_key: problem
  answer_key: answer
  image_key: images
  video_key: videos
  image_dir: null
  video_fps: 2.0
  max_prompt_length: 6144
  max_response_length: 2048
  rollout_batch_size: 512  # equivalent to verl's data.train_batch_size
  mini_rollout_batch_size: null  # equivalent to verl's data.gen_batch_size
  val_batch_size: 1024
  format_prompt: ./examples/format_prompt/math.jinja
  override_chat_template: null
  shuffle: true
  seed: 1
  min_pixels: 262144
  max_pixels: 262144
  filter_overlong_prompts: true

algorithm:
  adv_estimator: grpo
  disable_kl: false
  use_kl_loss: true
  kl_penalty: low_var_kl
  kl_coef: 1.0e-2
  online_filtering: false  # dapo filter groups
  filter_key: overall
  filter_low: 0.01
  filter_high: 0.99
  rollout_correction_bypass: false  # whether to set old_log_probs == log_probs during rollout data collection

worker:
  actor:
    global_batch_size: 128  # equivalent to verl's actor.ppo_mini_batch_size
    micro_batch_size_per_device_for_update: 1  # equivalent to verl's actor.ppo_micro_batch_size_per_gpu
    micro_batch_size_per_device_for_experience: 2  # equivalent to verl's rollout.log_prob_micro_batch_size_per_gpu
    max_grad_norm: 1.0
    padding_free: true
    dynamic_batching: true
    ulysses_size: 1
    model:
      model_path: Qwen/Qwen2.5-7B-Instruct
      enable_gradient_checkpointing: true
      trust_remote_code: false
      freeze_vision_tower: false
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
      strategy: adamw  # {adamw, adamw_bf16}
      lr_warmup_ratio: 0.0
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
    offload:
      offload_params: true  # true: more CPU memory; false: more GPU memory
      offload_optimizer: true  # true: more CPU memory; false: more GPU memory

  rollout:
    n: 5
    temperature: 1.0
    top_p: 1.0
    limit_images: 0
    gpu_memory_utilization: 0.6
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 1
    disable_tqdm: false
    val_override_config:
      temperature: 0.6
      top_p: 0.95
      n: 1
    calculate_log_probs: false # whether to calculate log probs of the rollout responses
    custom_rollout_flag: null # flag for custom rollout method. Will later be used in the rollout engine to determine rollout strategy.
    custom_rollout_args:
      # args for custom rollout method
      exp_r: 0.0 # exploration rate for rollout, 0.0 means no exploration
      batch_exp_r: 1.0 # exploration rate for a full rollout batch to explore. 0.5 means there's 50% chance to do exploration rollout of a batch. Within the batch, the model will do exploration with explore exp_r*rollout.n examples.
      mix_constraint_types: "batch" # ["batch", "data", "rollout"], each means that the reasoning type is mixed "under" this level.
      ctrlg_reasoning_type_list: null # a list for ctrlg reasoning type, e.g., ["Backwarding", "Reflection"]
    engine_kwargs: # inference engine parameters
      vllm:
        logits_processors: null # null means "use the engine default value", e.g., for ctrlg, use ctrlg_custom.Qwen3BaseCtrlgProcessorV1
        logprobs_mode: "processed_logprobs" # options: raw_logprobs, processed_logprobs, raw_logits, and processed_logits

  ref:
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: true  # true: more CPU memory; false: more GPU memory
      enable_rank0_init: true
    offload:
      offload_params: false

  reward:
    reward_function: ./examples/reward_function/r1v.py:compute_score

trainer:
  total_epochs: 15
  max_steps: null
  project_name: baselines
  experiment_name: qwen2_5_7b_math_grpo
  logger: ["file", "wandb"]
  nnodes: 1
  n_gpus_per_node: 8
  max_try_make_batch: 20  # -1 means no limit
  val_freq: 5  # -1 to disable
  val_before_train: false
  val_only: false
  val_generations_to_log: 3
  save_freq: 5  # -1 to disable
  save_limit: 3  # -1 to disable
  save_model_only: false
  save_checkpoint_path: null
  load_checkpoint_path: null
  find_last_checkpoint: true
